declare module 'vue-router/auto-routes' {
  import type { Router, RouteRecordRaw } from 'vue-router'

  /**
   * Array of routes generated by vite-plugin-routes
   */
  export const routes: RouteRecordRaw[]

  /**
   * Setups hot module replacement for routes.
   * @param router - The router instance
   * @param hotUpdateCallback - Callback to be called after replacing the routes and before the navigation
   * @example
   * ```ts
   * import { createRouter, createWebHistory } from 'vue-router'
   * import { routes, handleHotUpdate } from 'vue-router/auto-routes'
   * const router = createRouter({
   *   history: createWebHistory(),
   *   routes,
   * })
   * if (import.meta.hot) {
   * handleHotUpdate(router)
   * }
   * ```
   */
  // eslint-disable-next-line pickier/no-unused-vars
  export function handleHotUpdate(
    router: Router,
    hotUpdateCallback?: (newRoutes: RouteRecordRaw[]) => void,
  ): void
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto-routes'

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap
  }
}

// FIXME: remove vue-router/auto in next major

/**
 * @deprecated Directly import from 'vue-router' instead
 */
declare module 'vue-router/auto' {
  // Experimental Data Fetching
  export {
    DataLoaderPlugin,
    NavigationResult,
  } from 'vite-plugin-routes/data-loaders'

  export { definePage } from 'vite-plugin-routes/runtime'
  // reexport all types that are not augmented by vite-plugin-routes
  export * from 'vue-router'
  // must be added to the virtual vue-router/auto
  // FIXME: is there a way to achieve this without losing the types?
  // export { defineBasicLoader } from 'vite-plugin-routes/data-loaders/basic'
  // export { defineColadaLoader } from 'vite-plugin-routes/data-loaders/pinia-colada'
}

// Make the macros globally available
declare global {
  // eslint-disable-next-line pickier/no-unused-vars
  const definePage: (typeof import('vite-plugin-routes/runtime'))['definePage']
}

export {}
